---
- hosts: control
  strategy: free 
  gather_facts: False
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=control.ansi.example.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Building host file
    copy:
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.59 repo.ansi.example.com repo\n192.168.55.60 control.ansi.example.com control\n192.168.55.61 node1.ansi.example.com node1\n192.168.55.62 node2.ansi.example.com node2\n192.168.55.63 node3.ansi.example.com node3"
      dest: /etc/hosts
      force: yes
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Repo File
    file:
      path: /etc/yum.repos.d/rpms.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/rpms.repo
      block: |
       [rpms]
       name=rpms
       baseurl=http://repo/rpms/75rpms
       gpgcheck=0
       enabled=1
  - name: Starting Firewalld
    service: 
      name: "{{ item }}"
      enabled: true
      state: started
    with_items:
      - httpd
      - firewalld
      - chronyd
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http 
      - https 
      - ntp 
      - dns 
      - kerberos 
      - ldap 
      - ldaps 
      - ftp
  - name: Restarting Firewalld
    service: 
      name: firewalld
      state: restarted
  - name: Removing Existing RSA Key
    shell: rm -f /home/user/.ssh/id_rsa
  - name: Generating New RSA Key
    command: ssh-keygen -q -t rsa -f /home/user/.ssh/id_rsa -C "" -N ""
    args: 
      creates: /home/user/.ssh/id_rsa
    become_user: user
    become_method: sudo
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #            _            _           _          _           _          _           _     
        #          /\ \          /\ \        /\ \     _ /\ \        /\ \       /\ \        _\ \   
        #         /  \ \        /  \ \      /  \ \   /\_\_\ \      /  \ \     /  \ \      /\__ \  
        #        / /\ \ \      / /\ \ \    / /\ \ \_/ / /\__ \    / /\ \ \   / /\ \ \    / /_ \_\ 
        #       / / /\ \ \    / / /\ \ \  / / /\ \___/ / /_ \ \  / / /\ \_\ / / /\ \ \  / / /\/_/ 
        #      / / /  \ \_\  / / /  \ \_\/ / /  \/____/ / /\ \ \/ / /_/ / // / /  \ \_\/ / /      
        #     / / /    \/_/ / / /   / / / / /    / / / / /  \/_/ / /__\/ // / /   / / / / /       
        #    / / /         / / /   / / / / /    / / / / /     / / /_____// / /   / / / / / ____   
        #   / / /________ / / /___/ / / / /    / / / / /     / / /\ \ \ / / /___/ / / /_/_/ ___/\ 
        #  / / /_________/ / /____\/ / / /    / / /_/ /     / / /  \ \ / / /____\/ /_______/\__\/ 
        #  \/____________\/_________/\/_/     \/_/\_\/      \/_/    \_\\/_________/\_______\/     
        '"#
        #
        # You are logged into \"`hostname`\" as the \"`whoami`\" account.
        # This system is running `cat /etc/redhat-release`
        #
        # Repo
        # Available to use from http://repo.ansi.example.com/rpms/75rpms
        "