---
- hosts: repo
  strategy: free
  ignore_errors: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    hostname: name=repo.test.example.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Fixing Stupid SELinux
    sefcontext:
      target: '/var/www/html/rpms(/.*)?'
      setype: httpd_sys_content_t
      state: present
  - name: Ready Repo 1!
    command: createrepo /var/www/html/rpms/75rpms
  - name: Restoring Contexts
    command: restorecon -R /var/www/html/rpms/
  - name: Building host file
    copy:
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.60 control.test.example.com control\n192.168.55.59 repo.test.example.com repo\n192.168.55.61 node1.test.example.com node1\n192.168.55.62 node2.test.example.com node2\n192.168.55.63 node3.test.example.com node3"
      dest: /etc/hosts
      force: yes
  - name: Enabling services
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - firewalld
      - chronyd
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http 
      - https 
      - ntp 
      - dns 
      - kerberos 
      - ldap 
      - ldaps 
      - ftp
  - name: Reloading Firewall
    service: name=firewalld state=restarted
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into `hostname` as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         "
...